/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package health_tracker;

/**
 *
 * @author Asus
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRencanaMakan = new javax.swing.JButton();
        btnPelacakanAktivitas = new javax.swing.JButton();
        btnKontenEdukasi = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        setTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRencanaMakan.setText("Rencana Makan");
        btnRencanaMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRencanaMakanActionPerformed(evt);
            }
        });

        btnPelacakanAktivitas.setText("Pelacakan Aktivitas");
        btnPelacakanAktivitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelacakanAktivitasActionPerformed(evt);
            }
        });

        btnKontenEdukasi.setText("Konten Edukasi");
        btnKontenEdukasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKontenEdukasiActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        setTitle.setText("Menu Utama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKontenEdukasi, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPelacakanAktivitas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRencanaMakan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(setTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setTitle)
                .addGap(25, 25, 25)
                .addComponent(btnRencanaMakan)
                .addGap(18, 18, 18)
                .addComponent(btnPelacakanAktivitas)
                .addGap(18, 18, 18)
                .addComponent(btnKontenEdukasi)
                .addGap(18, 18, 18)
                .addComponent(btnKeluar)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRencanaMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRencanaMakanActionPerformed
        new Rencana_Makan().setVisible(true);
        new Rencana_Makan().setVisible(true); // Ganti dengan nama class register Anda
        this.dispose();
    }//GEN-LAST:event_btnRencanaMakanActionPerformed

    private void btnPelacakanAktivitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelacakanAktivitasActionPerformed
        new PelacakanAktivitas().setVisible(true);
        new PelacakanAktivitas().setVisible(true); // Ganti dengan nama class register Anda
        this.dispose();
    }//GEN-LAST:event_btnPelacakanAktivitasActionPerformed

    private void btnKontenEdukasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKontenEdukasiActionPerformed
        new KontenEdukasi().setVisible(true);
        new KontenEdukasi().setVisible(true); // Ganti dengan nama class register Anda
        this.dispose();
    }//GEN-LAST:event_btnKontenEdukasiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKontenEdukasi;
    private javax.swing.JButton btnPelacakanAktivitas;
    private javax.swing.JButton btnRencanaMakan;
    private javax.swing.JLabel setTitle;
    // End of variables declaration//GEN-END:variables
}
